// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies;

public class CSS
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cSSMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxCSS.CSS";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		name("name"),
		value("value"),
		idx("idx"),
		active("active"),
		_createdDate("_createdDate"),
		_changedDate("_changedDate"),
		Style_CSS_Compiled("MxCSS.Style_CSS_Compiled"),
		CSS_FileDocument("MxCSS.CSS_FileDocument");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CSS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxCSS.CSS"));
	}

	protected CSS(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cSSMendixObject)
	{
		if (cSSMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxCSS.CSS", cSSMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxCSS.CSS");

		this.cSSMendixObject = cSSMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CSS.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxcss.proxies.CSS initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxcss.proxies.CSS.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxcss.proxies.CSS initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxcss.proxies.CSS(context, mendixObject);
	}

	public static mxcss.proxies.CSS load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxcss.proxies.CSS.initialize(context, mendixObject);
	}

	public static java.util.List<mxcss.proxies.CSS> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mxcss.proxies.CSS> result = new java.util.ArrayList<mxcss.proxies.CSS>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MxCSS.CSS" + xpathConstraint))
			result.add(mxcss.proxies.CSS.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of value
	 */
	public final java.lang.String getvalue()
	{
		return getvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of value
	 */
	public final java.lang.String getvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.value.toString());
	}

	/**
	 * Set value of value
	 * @param value
	 */
	public final void setvalue(java.lang.String value)
	{
		setvalue(getContext(), value);
	}

	/**
	 * Set value of value
	 * @param context
	 * @param value
	 */
	public final void setvalue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.value.toString(), value);
	}

	/**
	 * @return value of idx
	 */
	public final java.lang.Integer getidx()
	{
		return getidx(getContext());
	}

	/**
	 * @param context
	 * @return value of idx
	 */
	public final java.lang.Integer getidx(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.idx.toString());
	}

	/**
	 * Set value of idx
	 * @param idx
	 */
	public final void setidx(java.lang.Integer idx)
	{
		setidx(getContext(), idx);
	}

	/**
	 * Set value of idx
	 * @param context
	 * @param idx
	 */
	public final void setidx(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer idx)
	{
		getMendixObject().setValue(context, MemberNames.idx.toString(), idx);
	}

	/**
	 * @return value of active
	 */
	public final java.lang.Boolean getactive()
	{
		return getactive(getContext());
	}

	/**
	 * @param context
	 * @return value of active
	 */
	public final java.lang.Boolean getactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.active.toString());
	}

	/**
	 * Set value of active
	 * @param active
	 */
	public final void setactive(java.lang.Boolean active)
	{
		setactive(getContext(), active);
	}

	/**
	 * Set value of active
	 * @param context
	 * @param active
	 */
	public final void setactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.active.toString(), active);
	}

	/**
	 * @return value of _createdDate
	 */
	public final java.util.Date get_createdDate()
	{
		return get_createdDate(getContext());
	}

	/**
	 * @param context
	 * @return value of _createdDate
	 */
	public final java.util.Date get_createdDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames._createdDate.toString());
	}

	/**
	 * Set value of _createdDate
	 * @param _createddate
	 */
	public final void set_createdDate(java.util.Date _createddate)
	{
		set_createdDate(getContext(), _createddate);
	}

	/**
	 * Set value of _createdDate
	 * @param context
	 * @param _createddate
	 */
	public final void set_createdDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date _createddate)
	{
		getMendixObject().setValue(context, MemberNames._createdDate.toString(), _createddate);
	}

	/**
	 * @return value of _changedDate
	 */
	public final java.util.Date get_changedDate()
	{
		return get_changedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of _changedDate
	 */
	public final java.util.Date get_changedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames._changedDate.toString());
	}

	/**
	 * Set value of _changedDate
	 * @param _changeddate
	 */
	public final void set_changedDate(java.util.Date _changeddate)
	{
		set_changedDate(getContext(), _changeddate);
	}

	/**
	 * Set value of _changedDate
	 * @param context
	 * @param _changeddate
	 */
	public final void set_changedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date _changeddate)
	{
		getMendixObject().setValue(context, MemberNames._changedDate.toString(), _changeddate);
	}

	/**
	 * @return value of Style_CSS_Compiled
	 */
	public final mxcss.proxies.Style getStyle_CSS_Compiled() throws com.mendix.core.CoreException
	{
		return getStyle_CSS_Compiled(getContext());
	}

	/**
	 * @param context
	 * @return value of Style_CSS_Compiled
	 */
	public final mxcss.proxies.Style getStyle_CSS_Compiled(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.Style result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Style_CSS_Compiled.toString());
		if (identifier != null)
			result = mxcss.proxies.Style.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Style_CSS_Compiled
	 * @param style_css_compiled
	 */
	public final void setStyle_CSS_Compiled(mxcss.proxies.Style style_css_compiled)
	{
		setStyle_CSS_Compiled(getContext(), style_css_compiled);
	}

	/**
	 * Set value of Style_CSS_Compiled
	 * @param context
	 * @param style_css_compiled
	 */
	public final void setStyle_CSS_Compiled(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.Style style_css_compiled)
	{
		if (style_css_compiled == null)
			getMendixObject().setValue(context, MemberNames.Style_CSS_Compiled.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Style_CSS_Compiled.toString(), style_css_compiled.getMendixObject().getId());
	}

	/**
	 * @return value of CSS_FileDocument
	 */
	public final mxcss.proxies.FileDocument getCSS_FileDocument() throws com.mendix.core.CoreException
	{
		return getCSS_FileDocument(getContext());
	}

	/**
	 * @param context
	 * @return value of CSS_FileDocument
	 */
	public final mxcss.proxies.FileDocument getCSS_FileDocument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.FileDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CSS_FileDocument.toString());
		if (identifier != null)
			result = mxcss.proxies.FileDocument.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CSS_FileDocument
	 * @param css_filedocument
	 */
	public final void setCSS_FileDocument(mxcss.proxies.FileDocument css_filedocument)
	{
		setCSS_FileDocument(getContext(), css_filedocument);
	}

	/**
	 * Set value of CSS_FileDocument
	 * @param context
	 * @param css_filedocument
	 */
	public final void setCSS_FileDocument(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.FileDocument css_filedocument)
	{
		if (css_filedocument == null)
			getMendixObject().setValue(context, MemberNames.CSS_FileDocument.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CSS_FileDocument.toString(), css_filedocument.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cSSMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxcss.proxies.CSS that = (mxcss.proxies.CSS) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxCSS.CSS";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
