// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies;

public enum enum_var_type
{
	_Int(new java.lang.String[][] { new java.lang.String[] { "en_US", "Int" } }),
	_Float(new java.lang.String[][] { new java.lang.String[] { "en_US", "Float" } }),
	String(new java.lang.String[][] { new java.lang.String[] { "en_US", "String" } }),
	Color(new java.lang.String[][] { new java.lang.String[] { "en_US", "Color" } }),
	_Boolean(new java.lang.String[][] { new java.lang.String[] { "en_US", "Boolean" } }),
	Value(new java.lang.String[][] { new java.lang.String[] { "en_US", "Value" } }),
	Pixels(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pixels" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private enum_var_type(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
