// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies;

public class FileDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxCSS.FileDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		CSS_FileDocument("MxCSS.CSS_FileDocument"),
		Sass("MxCSS.Sass");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FileDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxCSS.FileDocument"));
	}

	protected FileDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fileDocumentMendixObject)
	{
		super(context, fileDocumentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MxCSS.FileDocument", fileDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxCSS.FileDocument");
	}

	/**
	 * @deprecated Use 'FileDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxcss.proxies.FileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxcss.proxies.FileDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxcss.proxies.FileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxcss.proxies.FileDocument(context, mendixObject);
	}

	public static mxcss.proxies.FileDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxcss.proxies.FileDocument.initialize(context, mendixObject);
	}

	public static java.util.List<mxcss.proxies.FileDocument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mxcss.proxies.FileDocument> result = new java.util.ArrayList<mxcss.proxies.FileDocument>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MxCSS.FileDocument" + xpathConstraint))
			result.add(mxcss.proxies.FileDocument.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of CSS_FileDocument
	 */
	public final mxcss.proxies.CSS getCSS_FileDocument() throws com.mendix.core.CoreException
	{
		return getCSS_FileDocument(getContext());
	}

	/**
	 * @param context
	 * @return value of CSS_FileDocument
	 */
	public final mxcss.proxies.CSS getCSS_FileDocument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.CSS result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CSS_FileDocument.toString());
		if (identifier != null)
			result = mxcss.proxies.CSS.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CSS_FileDocument
	 * @param css_filedocument
	 */
	public final void setCSS_FileDocument(mxcss.proxies.CSS css_filedocument)
	{
		setCSS_FileDocument(getContext(), css_filedocument);
	}

	/**
	 * Set value of CSS_FileDocument
	 * @param context
	 * @param css_filedocument
	 */
	public final void setCSS_FileDocument(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.CSS css_filedocument)
	{
		if (css_filedocument == null)
			getMendixObject().setValue(context, MemberNames.CSS_FileDocument.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CSS_FileDocument.toString(), css_filedocument.getMendixObject().getId());
	}

	/**
	 * @return value of Sass
	 */
	public final mxcss.proxies.Style getSass() throws com.mendix.core.CoreException
	{
		return getSass(getContext());
	}

	/**
	 * @param context
	 * @return value of Sass
	 */
	public final mxcss.proxies.Style getSass(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.Style result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sass.toString());
		if (identifier != null)
			result = mxcss.proxies.Style.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Sass
	 * @param sass
	 */
	public final void setSass(mxcss.proxies.Style sass)
	{
		setSass(getContext(), sass);
	}

	/**
	 * Set value of Sass
	 * @param context
	 * @param sass
	 */
	public final void setSass(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.Style sass)
	{
		if (sass == null)
			getMendixObject().setValue(context, MemberNames.Sass.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Sass.toString(), sass.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxcss.proxies.FileDocument that = (mxcss.proxies.FileDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxCSS.FileDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
