// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies;

public class Find
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject findMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxCSS.Find";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Keyword("Keyword"),
		Replace("Replace"),
		Find_Style("MxCSS.Find_Style");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Find(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxCSS.Find"));
	}

	protected Find(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject findMendixObject)
	{
		if (findMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxCSS.Find", findMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxCSS.Find");

		this.findMendixObject = findMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Find.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxcss.proxies.Find initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxcss.proxies.Find.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxcss.proxies.Find initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxcss.proxies.Find(context, mendixObject);
	}

	public static mxcss.proxies.Find load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxcss.proxies.Find.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Keyword
	 */
	public final java.lang.String getKeyword()
	{
		return getKeyword(getContext());
	}

	/**
	 * @param context
	 * @return value of Keyword
	 */
	public final java.lang.String getKeyword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Keyword.toString());
	}

	/**
	 * Set value of Keyword
	 * @param keyword
	 */
	public final void setKeyword(java.lang.String keyword)
	{
		setKeyword(getContext(), keyword);
	}

	/**
	 * Set value of Keyword
	 * @param context
	 * @param keyword
	 */
	public final void setKeyword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String keyword)
	{
		getMendixObject().setValue(context, MemberNames.Keyword.toString(), keyword);
	}

	/**
	 * @return value of Replace
	 */
	public final java.lang.String getReplace()
	{
		return getReplace(getContext());
	}

	/**
	 * @param context
	 * @return value of Replace
	 */
	public final java.lang.String getReplace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Replace.toString());
	}

	/**
	 * Set value of Replace
	 * @param replace
	 */
	public final void setReplace(java.lang.String replace)
	{
		setReplace(getContext(), replace);
	}

	/**
	 * Set value of Replace
	 * @param context
	 * @param replace
	 */
	public final void setReplace(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String replace)
	{
		getMendixObject().setValue(context, MemberNames.Replace.toString(), replace);
	}

	/**
	 * @return value of Find_Style
	 */
	public final mxcss.proxies.Style getFind_Style() throws com.mendix.core.CoreException
	{
		return getFind_Style(getContext());
	}

	/**
	 * @param context
	 * @return value of Find_Style
	 */
	public final mxcss.proxies.Style getFind_Style(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.Style result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Find_Style.toString());
		if (identifier != null)
			result = mxcss.proxies.Style.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Find_Style
	 * @param find_style
	 */
	public final void setFind_Style(mxcss.proxies.Style find_style)
	{
		setFind_Style(getContext(), find_style);
	}

	/**
	 * Set value of Find_Style
	 * @param context
	 * @param find_style
	 */
	public final void setFind_Style(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.Style find_style)
	{
		if (find_style == null)
			getMendixObject().setValue(context, MemberNames.Find_Style.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Find_Style.toString(), find_style.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return findMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxcss.proxies.Find that = (mxcss.proxies.Find) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxCSS.Find";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
