// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies;

public class Style
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject styleMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxCSS.Style";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		name("name"),
		liveRefresh("liveRefresh"),
		_createdDate("_createdDate"),
		_changedDate("_changedDate"),
		Style_CSS("MxCSS.Style_CSS"),
		_default("MxCSS._default"),
		Replacement("MxCSS.Replacement"),
		Style_CSS_Compiled("MxCSS.Style_CSS_Compiled"),
		Sass("MxCSS.Sass");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Style(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxCSS.Style"));
	}

	protected Style(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject styleMendixObject)
	{
		if (styleMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxCSS.Style", styleMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxCSS.Style");

		this.styleMendixObject = styleMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Style.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxcss.proxies.Style initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxcss.proxies.Style.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxcss.proxies.Style initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxcss.proxies.Style(context, mendixObject);
	}

	public static mxcss.proxies.Style load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxcss.proxies.Style.initialize(context, mendixObject);
	}

	public static java.util.List<mxcss.proxies.Style> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mxcss.proxies.Style> result = new java.util.ArrayList<mxcss.proxies.Style>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MxCSS.Style" + xpathConstraint))
			result.add(mxcss.proxies.Style.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of liveRefresh
	 */
	public final java.lang.Boolean getliveRefresh()
	{
		return getliveRefresh(getContext());
	}

	/**
	 * @param context
	 * @return value of liveRefresh
	 */
	public final java.lang.Boolean getliveRefresh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.liveRefresh.toString());
	}

	/**
	 * Set value of liveRefresh
	 * @param liverefresh
	 */
	public final void setliveRefresh(java.lang.Boolean liverefresh)
	{
		setliveRefresh(getContext(), liverefresh);
	}

	/**
	 * Set value of liveRefresh
	 * @param context
	 * @param liverefresh
	 */
	public final void setliveRefresh(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean liverefresh)
	{
		getMendixObject().setValue(context, MemberNames.liveRefresh.toString(), liverefresh);
	}

	/**
	 * @return value of _createdDate
	 */
	public final java.util.Date get_createdDate()
	{
		return get_createdDate(getContext());
	}

	/**
	 * @param context
	 * @return value of _createdDate
	 */
	public final java.util.Date get_createdDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames._createdDate.toString());
	}

	/**
	 * Set value of _createdDate
	 * @param _createddate
	 */
	public final void set_createdDate(java.util.Date _createddate)
	{
		set_createdDate(getContext(), _createddate);
	}

	/**
	 * Set value of _createdDate
	 * @param context
	 * @param _createddate
	 */
	public final void set_createdDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date _createddate)
	{
		getMendixObject().setValue(context, MemberNames._createdDate.toString(), _createddate);
	}

	/**
	 * @return value of _changedDate
	 */
	public final java.util.Date get_changedDate()
	{
		return get_changedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of _changedDate
	 */
	public final java.util.Date get_changedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames._changedDate.toString());
	}

	/**
	 * Set value of _changedDate
	 * @param _changeddate
	 */
	public final void set_changedDate(java.util.Date _changeddate)
	{
		set_changedDate(getContext(), _changeddate);
	}

	/**
	 * Set value of _changedDate
	 * @param context
	 * @param _changeddate
	 */
	public final void set_changedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date _changeddate)
	{
		getMendixObject().setValue(context, MemberNames._changedDate.toString(), _changeddate);
	}

	/**
	 * @return value of Style_CSS
	 */
	public final java.util.List<mxcss.proxies.CSS> getStyle_CSS() throws com.mendix.core.CoreException
	{
		return getStyle_CSS(getContext());
	}

	/**
	 * @param context
	 * @return value of Style_CSS
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mxcss.proxies.CSS> getStyle_CSS(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mxcss.proxies.CSS> result = new java.util.ArrayList<mxcss.proxies.CSS>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Style_CSS.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(mxcss.proxies.CSS.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Style_CSS
	 * @param style_css
	 */
	public final void setStyle_CSS(java.util.List<mxcss.proxies.CSS> style_css)
	{
		setStyle_CSS(getContext(), style_css);
	}

	/**
	 * Set value of Style_CSS
	 * @param context
	 * @param style_css
	 */
	public final void setStyle_CSS(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mxcss.proxies.CSS> style_css)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (mxcss.proxies.CSS proxyObject : style_css)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Style_CSS.toString(), identifiers);
	}

	/**
	 * @return value of _default
	 */
	public final mxcss.proxies.Config get_default() throws com.mendix.core.CoreException
	{
		return get_default(getContext());
	}

	/**
	 * @param context
	 * @return value of _default
	 */
	public final mxcss.proxies.Config get_default(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.Config result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames._default.toString());
		if (identifier != null)
			result = mxcss.proxies.Config.load(context, identifier);
		return result;
	}

	/**
	 * Set value of _default
	 * @param _default
	 */
	public final void set_default(mxcss.proxies.Config _default)
	{
		set_default(getContext(), _default);
	}

	/**
	 * Set value of _default
	 * @param context
	 * @param _default
	 */
	public final void set_default(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.Config _default)
	{
		if (_default == null)
			getMendixObject().setValue(context, MemberNames._default.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames._default.toString(), _default.getMendixObject().getId());
	}

	/**
	 * @return value of Replacement
	 */
	public final mxcss.proxies.Style getReplacement() throws com.mendix.core.CoreException
	{
		return getReplacement(getContext());
	}

	/**
	 * @param context
	 * @return value of Replacement
	 */
	public final mxcss.proxies.Style getReplacement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.Style result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Replacement.toString());
		if (identifier != null)
			result = mxcss.proxies.Style.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Replacement
	 * @param replacement
	 */
	public final void setReplacement(mxcss.proxies.Style replacement)
	{
		setReplacement(getContext(), replacement);
	}

	/**
	 * Set value of Replacement
	 * @param context
	 * @param replacement
	 */
	public final void setReplacement(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.Style replacement)
	{
		if (replacement == null)
			getMendixObject().setValue(context, MemberNames.Replacement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Replacement.toString(), replacement.getMendixObject().getId());
	}

	/**
	 * @return value of Style_CSS_Compiled
	 */
	public final mxcss.proxies.CSS getStyle_CSS_Compiled() throws com.mendix.core.CoreException
	{
		return getStyle_CSS_Compiled(getContext());
	}

	/**
	 * @param context
	 * @return value of Style_CSS_Compiled
	 */
	public final mxcss.proxies.CSS getStyle_CSS_Compiled(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.CSS result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Style_CSS_Compiled.toString());
		if (identifier != null)
			result = mxcss.proxies.CSS.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Style_CSS_Compiled
	 * @param style_css_compiled
	 */
	public final void setStyle_CSS_Compiled(mxcss.proxies.CSS style_css_compiled)
	{
		setStyle_CSS_Compiled(getContext(), style_css_compiled);
	}

	/**
	 * Set value of Style_CSS_Compiled
	 * @param context
	 * @param style_css_compiled
	 */
	public final void setStyle_CSS_Compiled(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.CSS style_css_compiled)
	{
		if (style_css_compiled == null)
			getMendixObject().setValue(context, MemberNames.Style_CSS_Compiled.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Style_CSS_Compiled.toString(), style_css_compiled.getMendixObject().getId());
	}

	/**
	 * @return value of Sass
	 */
	public final mxcss.proxies.FileDocument getSass() throws com.mendix.core.CoreException
	{
		return getSass(getContext());
	}

	/**
	 * @param context
	 * @return value of Sass
	 */
	public final mxcss.proxies.FileDocument getSass(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.FileDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sass.toString());
		if (identifier != null)
			result = mxcss.proxies.FileDocument.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Sass
	 * @param sass
	 */
	public final void setSass(mxcss.proxies.FileDocument sass)
	{
		setSass(getContext(), sass);
	}

	/**
	 * Set value of Sass
	 * @param context
	 * @param sass
	 */
	public final void setSass(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.FileDocument sass)
	{
		if (sass == null)
			getMendixObject().setValue(context, MemberNames.Sass.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Sass.toString(), sass.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return styleMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxcss.proxies.Style that = (mxcss.proxies.Style) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxCSS.Style";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
