// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies;

public class Value
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject valueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxCSS.Value";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		idx("idx"),
		Var_Value("MxCSS.Var_Value");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxCSS.Value"));
	}

	protected Value(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject valueMendixObject)
	{
		if (valueMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxCSS.Value", valueMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxCSS.Value");

		this.valueMendixObject = valueMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Value.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxcss.proxies.Value initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxcss.proxies.Value.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxcss.proxies.Value initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("MxCSS._Boolean", mendixObject.getType()))
			return mxcss.proxies._Boolean.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("MxCSS._Color", mendixObject.getType()))
			return mxcss.proxies._Color.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("MxCSS._Float", mendixObject.getType()))
			return mxcss.proxies._Float.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("MxCSS._Int", mendixObject.getType()))
			return mxcss.proxies._Int.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("MxCSS._Pixels", mendixObject.getType()))
			return mxcss.proxies._Pixels.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("MxCSS._String", mendixObject.getType()))
			return mxcss.proxies._String.initialize(context, mendixObject);

		return new mxcss.proxies.Value(context, mendixObject);
	}

	public static mxcss.proxies.Value load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxcss.proxies.Value.initialize(context, mendixObject);
	}

	public static java.util.List<? extends mxcss.proxies.Value> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mxcss.proxies.Value> result = new java.util.ArrayList<mxcss.proxies.Value>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MxCSS.Value" + xpathConstraint))
			result.add(mxcss.proxies.Value.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of idx
	 */
	public final java.lang.Integer getidx()
	{
		return getidx(getContext());
	}

	/**
	 * @param context
	 * @return value of idx
	 */
	public final java.lang.Integer getidx(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.idx.toString());
	}

	/**
	 * Set value of idx
	 * @param idx
	 */
	public final void setidx(java.lang.Integer idx)
	{
		setidx(getContext(), idx);
	}

	/**
	 * Set value of idx
	 * @param context
	 * @param idx
	 */
	public final void setidx(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer idx)
	{
		getMendixObject().setValue(context, MemberNames.idx.toString(), idx);
	}

	/**
	 * @return value of Var_Value
	 */
	public final mxcss.proxies.Var getVar_Value() throws com.mendix.core.CoreException
	{
		return getVar_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Var_Value
	 */
	public final mxcss.proxies.Var getVar_Value(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.Var result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Var_Value.toString());
		if (identifier != null)
			result = mxcss.proxies.Var.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Var_Value
	 * @param var_value
	 */
	public final void setVar_Value(mxcss.proxies.Var var_value)
	{
		setVar_Value(getContext(), var_value);
	}

	/**
	 * Set value of Var_Value
	 * @param context
	 * @param var_value
	 */
	public final void setVar_Value(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.Var var_value)
	{
		if (var_value == null)
			getMendixObject().setValue(context, MemberNames.Var_Value.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Var_Value.toString(), var_value.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return valueMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxcss.proxies.Value that = (mxcss.proxies.Value) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxCSS.Value";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
