// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies;

/**
 * Variables to be used by jsass
 */
public class Var
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject varMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxCSS.Var";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Value("Value"),
		Idx("Idx"),
		_Type("_Type"),
		Enabled("Enabled"),
		Var_Style("MxCSS.Var_Style"),
		Var_Value("MxCSS.Var_Value");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Var(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxCSS.Var"));
	}

	protected Var(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject varMendixObject)
	{
		if (varMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxCSS.Var", varMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxCSS.Var");

		this.varMendixObject = varMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Var.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxcss.proxies.Var initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxcss.proxies.Var.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxcss.proxies.Var initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxcss.proxies.Var(context, mendixObject);
	}

	public static mxcss.proxies.Var load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxcss.proxies.Var.initialize(context, mendixObject);
	}

	public static java.util.List<mxcss.proxies.Var> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mxcss.proxies.Var> result = new java.util.ArrayList<mxcss.proxies.Var>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MxCSS.Var" + xpathConstraint))
			result.add(mxcss.proxies.Var.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of Idx
	 */
	public final java.lang.Integer getIdx()
	{
		return getIdx(getContext());
	}

	/**
	 * @param context
	 * @return value of Idx
	 */
	public final java.lang.Integer getIdx(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Idx.toString());
	}

	/**
	 * Set value of Idx
	 * @param idx
	 */
	public final void setIdx(java.lang.Integer idx)
	{
		setIdx(getContext(), idx);
	}

	/**
	 * Set value of Idx
	 * @param context
	 * @param idx
	 */
	public final void setIdx(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer idx)
	{
		getMendixObject().setValue(context, MemberNames.Idx.toString(), idx);
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final mxcss.proxies.enum_var_type get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final mxcss.proxies.enum_var_type get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames._Type.toString());
		if (obj == null)
			return null;

		return mxcss.proxies.enum_var_type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(mxcss.proxies.enum_var_type _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.enum_var_type _type)
	{
		if (_type != null)
			getMendixObject().setValue(context, MemberNames._Type.toString(), _type.toString());
		else
			getMendixObject().setValue(context, MemberNames._Type.toString(), null);
	}

	/**
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled()
	{
		return getEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Enabled.toString());
	}

	/**
	 * Set value of Enabled
	 * @param enabled
	 */
	public final void setEnabled(java.lang.Boolean enabled)
	{
		setEnabled(getContext(), enabled);
	}

	/**
	 * Set value of Enabled
	 * @param context
	 * @param enabled
	 */
	public final void setEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enabled)
	{
		getMendixObject().setValue(context, MemberNames.Enabled.toString(), enabled);
	}

	/**
	 * @return value of Var_Style
	 */
	public final mxcss.proxies.Style getVar_Style() throws com.mendix.core.CoreException
	{
		return getVar_Style(getContext());
	}

	/**
	 * @param context
	 * @return value of Var_Style
	 */
	public final mxcss.proxies.Style getVar_Style(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.Style result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Var_Style.toString());
		if (identifier != null)
			result = mxcss.proxies.Style.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Var_Style
	 * @param var_style
	 */
	public final void setVar_Style(mxcss.proxies.Style var_style)
	{
		setVar_Style(getContext(), var_style);
	}

	/**
	 * Set value of Var_Style
	 * @param context
	 * @param var_style
	 */
	public final void setVar_Style(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.Style var_style)
	{
		if (var_style == null)
			getMendixObject().setValue(context, MemberNames.Var_Style.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Var_Style.toString(), var_style.getMendixObject().getId());
	}

	/**
	 * @return value of Var_Value
	 */
	public final mxcss.proxies.Value getVar_Value() throws com.mendix.core.CoreException
	{
		return getVar_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Var_Value
	 */
	public final mxcss.proxies.Value getVar_Value(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxcss.proxies.Value result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Var_Value.toString());
		if (identifier != null)
			result = mxcss.proxies.Value.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Var_Value
	 * @param var_value
	 */
	public final void setVar_Value(mxcss.proxies.Value var_value)
	{
		setVar_Value(getContext(), var_value);
	}

	/**
	 * Set value of Var_Value
	 * @param context
	 * @param var_value
	 */
	public final void setVar_Value(com.mendix.systemwideinterfaces.core.IContext context, mxcss.proxies.Value var_value)
	{
		if (var_value == null)
			getMendixObject().setValue(context, MemberNames.Var_Value.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Var_Value.toString(), var_value.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return varMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxcss.proxies.Var that = (mxcss.proxies.Var) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxCSS.Var";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
