// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxcss.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class DeepClone extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject source;
	private IMendixObject target;
	private java.lang.String membersToSkip;
	private java.lang.String membersToKeep;
	private java.lang.String reverseAssociations;
	private java.lang.String excludeEntities;
	private java.lang.String excludeModules;

	public DeepClone(IContext context, IMendixObject source, IMendixObject target, java.lang.String membersToSkip, java.lang.String membersToKeep, java.lang.String reverseAssociations, java.lang.String excludeEntities, java.lang.String excludeModules)
	{
		super(context);
		this.source = source;
		this.target = target;
		this.membersToSkip = membersToSkip;
		this.membersToKeep = membersToKeep;
		this.reverseAssociations = reverseAssociations;
		this.excludeEntities = excludeEntities;
		this.excludeModules = excludeModules;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeepClone";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
