// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxcss.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class StringFromFile extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __source;
	private system.proxies.FileDocument source;

	public StringFromFile(IContext context, IMendixObject source)
	{
		super(context);
		this.__source = source;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.source = __source == null ? null : system.proxies.FileDocument.initialize(getContext(), __source);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringFromFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
