// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MxCSS module

	/**
	* deployment/web/styles/css/lib/lib.css
	*/
	public static java.lang.String getconst_lib_css()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MxCSS.const_lib_css");
	}
}