// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxcss.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MxCSS module
	public static void aco_css(IContext context, mxcss.proxies.CSS _cSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CSS", _cSS == null ? null : _cSS.getMendixObject());
			Core.execute(context, "MxCSS.aco_css", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean acr_css(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MxCSS.acr_css", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean acr_style(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MxCSS.acr_style", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bco_css(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MxCSS.bco_css", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bco_style(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MxCSS.bco_style", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bco_var(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MxCSS.bco_var", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Config ds_config(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_config", params);
			return result == null ? null : mxcss.proxies.Config.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Style ds_config_style_default(IContext context, mxcss.proxies.Config _obj_Config)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Config", _obj_Config == null ? null : _obj_Config.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_config_style_default", params);
			return result == null ? null : mxcss.proxies.Style.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.CSS ds_css_for_style_findbyname(IContext context, java.lang.String _name, mxcss.proxies.Style _style, java.lang.String _value, java.lang.Long _idx)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("name", _name);
			params.put("style", _style == null ? null : _style.getMendixObject());
			params.put("value", _value);
			params.put("idx", _idx);
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_css_for_style_findbyname", params);
			return result == null ? null : mxcss.proxies.CSS.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.FileDocument ds_filedocument(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_filedocument", params);
			return result == null ? null : mxcss.proxies.FileDocument.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.FileDocument ds_filedocument_theme(IContext context, java.lang.String _url)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("url", _url);
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_filedocument_theme", params);
			return result == null ? null : mxcss.proxies.FileDocument.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Find ds_find(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_find", params);
			return result == null ? null : mxcss.proxies.Find.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Host ds_host(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_host", params);
			return result == null ? null : mxcss.proxies.Host.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.KV ds_kv(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_kv", params);
			return result == null ? null : mxcss.proxies.KV.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Style ds_style_default(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_style_default", params);
			return result == null ? null : mxcss.proxies.Style.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Style ds_style_findbyname(IContext context, java.lang.String _str_name)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("str_name", _str_name);
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_style_findbyname", params);
			return result == null ? null : mxcss.proxies.Style.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Var ds_var(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ds_var", params);
			return result == null ? null : mxcss.proxies.Var.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String ivk_ace_css_w(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			return (java.lang.String)Core.execute(context, "MxCSS.ivk_ace_css_w", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String ivk_ace_css_wq(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			return (java.lang.String)Core.execute(context, "MxCSS.ivk_ace_css_wq", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String ivk_css_ace_q(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			return (java.lang.String)Core.execute(context, "MxCSS.ivk_css_ace_q", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_active_toggle(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			Core.execute(context, "MxCSS.ivk_css_active_toggle", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_arr_export(IContext context, java.util.List<mxcss.proxies.CSS> _arr_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_arr_CSS = null;
			if (_arr_CSS != null)
			{
				listparam_arr_CSS = new java.util.ArrayList<IMendixObject>();
				for (mxcss.proxies.CSS obj : _arr_CSS)
					listparam_arr_CSS.add(obj.getMendixObject());
			}
			params.put("arr_CSS", listparam_arr_CSS);
			Core.execute(context, "MxCSS.ivk_css_arr_export", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_arr_import(IContext context, mxcss.proxies.FileDocument _obj_FileDocument)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_FileDocument", _obj_FileDocument == null ? null : _obj_FileDocument.getMendixObject());
			Core.execute(context, "MxCSS.ivk_css_arr_import", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_drop(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MxCSS.ivk_css_drop", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_idx_dec(IContext context, mxcss.proxies.CSS _obj_CSS_src, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS_src", _obj_CSS_src == null ? null : _obj_CSS_src.getMendixObject());
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_css_idx_dec", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_idx_inc(IContext context, mxcss.proxies.CSS _obj_CSS_src, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS_src", _obj_CSS_src == null ? null : _obj_CSS_src.getMendixObject());
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_css_idx_inc", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_obj_export(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			Core.execute(context, "MxCSS.ivk_css_obj_export", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_obj_import(IContext context, mxcss.proxies.FileDocument _obj_FileDocument)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_FileDocument", _obj_FileDocument == null ? null : _obj_FileDocument.getMendixObject());
			Core.execute(context, "MxCSS.ivk_css_obj_import", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_saveforrefresh_gui(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			Core.execute(context, "MxCSS.ivk_css_saveforrefresh_gui", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_css_xfer(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			Core.execute(context, "MxCSS.ivk_css_xfer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean ivk_css2filedocument(IContext context, mxcss.proxies.FileDocument _fileDocument, mxcss.proxies.CSS _cSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("FileDocument", _fileDocument == null ? null : _fileDocument.getMendixObject());
			params.put("CSS", _cSS == null ? null : _cSS.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MxCSS.ivk_css2filedocument", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String ivk_css2string(IContext context, mxcss.proxies.CSS _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			return (java.lang.String)Core.execute(context, "MxCSS.ivk_css2string", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_filedocument2css(IContext context, mxcss.proxies.FileDocument _fileDocument, mxcss.proxies.CSS _cSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("FileDocument", _fileDocument == null ? null : _fileDocument.getMendixObject());
			params.put("CSS", _cSS == null ? null : _cSS.getMendixObject());
			Core.execute(context, "MxCSS.ivk_filedocument2css", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_find(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_find", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_host_toggleActive(IContext context, mxcss.proxies.Host _obj_Host)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Host", _obj_Host == null ? null : _obj_Host.getMendixObject());
			Core.execute(context, "MxCSS.ivk_host_toggleActive", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean ivk_init(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "MxCSS.ivk_init", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_json_export_css(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MxCSS.ivk_json_export_css", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_json_export_style_arr(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MxCSS.ivk_json_export_style_arr", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_json_export_style_obj(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_json_export_style_obj", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_json_import_css_0(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MxCSS.ivk_json_import_css_0", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_json_import_css_1(IContext context, mxcss.proxies.FileDocument _obj_FileDocument)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_FileDocument", _obj_FileDocument == null ? null : _obj_FileDocument.getMendixObject());
			Core.execute(context, "MxCSS.ivk_json_import_css_1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_json_import_style_0(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MxCSS.ivk_json_import_style_0", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_json_import_style_1(IContext context, mxcss.proxies.FileDocument _obj_FileDocument)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_FileDocument", _obj_FileDocument == null ? null : _obj_FileDocument.getMendixObject());
			Core.execute(context, "MxCSS.ivk_json_import_style_1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_kbd_style_refresh_client(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_kbd_style_refresh_client", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_plainntext_overwrite_0(IContext context, mxcss.proxies.CSS _cSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CSS", _cSS == null ? null : _cSS.getMendixObject());
			Core.execute(context, "MxCSS.ivk_plainntext_overwrite_0", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_plainntext_overwrite_1(IContext context, mxcss.proxies.CSS _cSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CSS", _cSS == null ? null : _cSS.getMendixObject());
			Core.execute(context, "MxCSS.ivk_plainntext_overwrite_1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_plaintext_import_0(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MxCSS.ivk_plaintext_import_0", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_plaintext_import_1(IContext context, mxcss.proxies.FileDocument _obj_FileDocument)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_FileDocument", _obj_FileDocument == null ? null : _obj_FileDocument.getMendixObject());
			Core.execute(context, "MxCSS.ivk_plaintext_import_1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_replace(IContext context, mxcss.proxies.Find _obj_Find)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Find", _obj_Find == null ? null : _obj_Find.getMendixObject());
			Core.execute(context, "MxCSS.ivk_replace", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String ivk_rest_css_default(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
			return (java.lang.String)Core.execute(context, "MxCSS.ivk_rest_css_default", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String ivk_rest_style_create(IContext context, java.util.List<mxcss.proxies.Style> _arr_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_arr_Style = null;
			if (_arr_Style != null)
			{
				listparam_arr_Style = new java.util.ArrayList<IMendixObject>();
				for (mxcss.proxies.Style obj : _arr_Style)
					listparam_arr_Style.add(obj.getMendixObject());
			}
			params.put("arr_Style", listparam_arr_Style);
			return (java.lang.String)Core.execute(context, "MxCSS.ivk_rest_style_create", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_rest_Style_xfer(IContext context, mxcss.proxies.Host _host, java.util.List<mxcss.proxies.Style> _arr_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Host", _host == null ? null : _host.getMendixObject());
			java.util.ArrayList<IMendixObject> listparam_arr_Style = null;
			if (_arr_Style != null)
			{
				listparam_arr_Style = new java.util.ArrayList<IMendixObject>();
				for (mxcss.proxies.Style obj : _arr_Style)
					listparam_arr_Style.add(obj.getMendixObject());
			}
			params.put("arr_Style", listparam_arr_Style);
			Core.execute(context, "MxCSS.ivk_rest_Style_xfer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_search(IContext context, mxcss.proxies.Find _obj_Find)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Find", _obj_Find == null ? null : _obj_Find.getMendixObject());
			Core.execute(context, "MxCSS.ivk_search", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Style ivk_session_getStyle(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ivk_session_getStyle", params);
			return result == null ? null : mxcss.proxies.Style.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxcss.proxies.Style> ivk_session_getstyle_arr(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "MxCSS.ivk_session_getstyle_arr", params);
			java.util.List<mxcss.proxies.Style> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxcss.proxies.Style>();
				for (IMendixObject obj : objs)
					result.add(mxcss.proxies.Style.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String ivk_session_getstyle_string(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.String)Core.execute(context, "MxCSS.ivk_session_getstyle_string", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_arr_export(IContext context, java.util.List<mxcss.proxies.Style> _arr_Style, java.lang.String _str_name)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_arr_Style = null;
			if (_arr_Style != null)
			{
				listparam_arr_Style = new java.util.ArrayList<IMendixObject>();
				for (mxcss.proxies.Style obj : _arr_Style)
					listparam_arr_Style.add(obj.getMendixObject());
			}
			params.put("arr_Style", listparam_arr_Style);
			params.put("str_name", _str_name);
			Core.execute(context, "MxCSS.ivk_style_arr_export", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_arr_import(IContext context, mxcss.proxies.FileDocument _obj_FileDocument)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_FileDocument", _obj_FileDocument == null ? null : _obj_FileDocument.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_arr_import", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Style ivk_style_createdefault(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ivk_style_createdefault", params);
			return result == null ? null : mxcss.proxies.Style.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_css_new_gui(IContext context, mxcss.proxies.Style _style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Style", _style == null ? null : _style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_css_new_gui", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_css_toggle_active(IContext context, mxcss.proxies.Style _obj_CSS)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_CSS", _obj_CSS == null ? null : _obj_CSS.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_css_toggle_active", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_drop(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MxCSS.ivk_style_drop", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_drop_css(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_drop_css", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Style ivk_style_duplicate(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ivk_style_duplicate", params);
			return result == null ? null : mxcss.proxies.Style.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_duplicate_gui(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_duplicate_gui", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_obj_export(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_obj_export", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_obj_import(IContext context, mxcss.proxies.FileDocument _obj_FileDocument)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_FileDocument", _obj_FileDocument == null ? null : _obj_FileDocument.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_obj_import", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxcss.proxies.Style ivk_style_replacecss(IContext context, mxcss.proxies.Style _obj_Style_src, mxcss.proxies.Style _obj_Style_tgt)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style_src", _obj_Style_src == null ? null : _obj_Style_src.getMendixObject());
			params.put("obj_Style_tgt", _obj_Style_tgt == null ? null : _obj_Style_tgt.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MxCSS.ivk_style_replacecss", params);
			return result == null ? null : mxcss.proxies.Style.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_replacecss_gui(IContext context, mxcss.proxies.Style _obj_Style_tgt)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style_tgt", _obj_Style_tgt == null ? null : _obj_Style_tgt.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_replacecss_gui", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_saveforrefresh_gui(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_saveforrefresh_gui", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_setdefault(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_setdefault", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_style_xfer(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_style_xfer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String ivk_style2string(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			return (java.lang.String)Core.execute(context, "MxCSS.ivk_style2string", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_delete(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_delete", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_new(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_new", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_set_boolean(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_set_boolean", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_set_color(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_set_color", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_set_float(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_set_float", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_set_int(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_set_int", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_set_pixels(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_set_pixels", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_set_string(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_set_string", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_set_value(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_set_value", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_settype(IContext context, mxcss.proxies.Var _obj_Var, mxcss.proxies.enum_var_type _enum_var_type)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			params.put("enum_var_type", _enum_var_type == null ? null : _enum_var_type.name());
			Core.execute(context, "MxCSS.ivk_var_settype", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_var_toggleEnabled(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.ivk_var_toggleEnabled", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_xfer(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MxCSS.ivk_xfer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void och_style(IContext context, mxcss.proxies.Style _obj_Style)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Style", _obj_Style == null ? null : _obj_Style.getMendixObject());
			Core.execute(context, "MxCSS.och_style", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean och_value(IContext context, mxcss.proxies.Value _obj_Value)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Value", _obj_Value == null ? null : _obj_Value.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MxCSS.och_value", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void och_var(IContext context, mxcss.proxies.Var _obj_Var)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_Var", _obj_Var == null ? null : _obj_Var.getMendixObject());
			Core.execute(context, "MxCSS.och_var", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}